### ISSUE TITLE
[H2] Minimum depth is actually 11.8m in latest 1deg and 0.25deg topo

### ISSUE THREAD

**Issue by aekiss** [willaguiar/DSW-collaborative-project#12]
I'm a bit confused by [H2](https://github.com/willaguiar/DSW-collaborative-project#h2----fine-ocean-vertical-resolution). The 1deg and 0.25deg topography in the latest configurations has a minimum depth of 11.8m (4 cells), not 40m - see [here](https://github.com/COSIMA/access-om2/issues/158#issuecomment-714267777).

Which topography files are you using? If you're using really old topography with 40m min depth, why not switch to the new one to test this hypothesis? That seems easier than modifying the 0.1 topography.

Also be aware that the new 0.25deg topo had some errors around the Antarctic coast. These have been fixed, but the fix is not yet in the standard 0.25 configs - see https://github.com/COSIMA/access-om2/issues/265

**Comment by willaguiar** [comment]
Hi @aekiss 
I got the 40m value from **ht** in /g/data/ik11/outputs/access-om2-025/025deg_jra55_ryf9091_gadi/output300/ocean/ocean_grid.nc (Sorry - didn't know it changed it after that).

I will change the H2 description then. (is **ht** in /g/data/ik11/outputs/access-om2-025/025deg_jra55_iaf_omip2_cycle3/output160/ocean/ocean_grid.nc the current topography used?)

**Comment by aekiss** [comment]
`/g/data/ik11/outputs/access-om2-025/025deg_jra55_ryf9091_gadi/output300`
uses 
`/g/data/ik11/inputs/access-om2/input_20200530/mom_025deg/topog.nc` 
(you can find this out from the ocean input in `config.yaml`).
This is an old topography that has 40m min depth and lots of other problems - see https://github.com/COSIMA/access-om2/issues/158

The very latest 0.25 topog is
`/g/data/ik11/inputs/access-om2/input_20220919_025deg_topog/mom_025deg/topog.nc`
and is used on the `update_antarctic_topo` branch at https://github.com/COSIMA/025deg_jra55_ryf/tree/update_antarctic_topo
the one in the master branch is older, but still has 11.8m minimum depth
see https://github.com/COSIMA/025deg_jra55_ryf/blob/master/config.yaml#L31

See https://github.com/COSIMA/access-om2/issues/265#issuecomment-1251654228

**Comment by adele157** [comment]
I think the H2 description would be simpler if we don't mention the 025 model at all. It's not really needed. e.g. how about this instead:

"ACCESS-OM2-01  has a high vertical resolution in upper ocean (e.g. upper cell thickness of ~1m). The vertical resolution in OM2-01 might be optimal to allow DSW formation along the shelf and to permit shelf overflows without excessive mixing. We want to coarsen the vertical resolution of OM2-01 (to an upper cell thickness of 5m) to see if that suppresses DSW formation and its overflow. This will also require modification of the bathymetry's minimum depth (currently ~10m minimum), so that we still have a minimum of 4 cells deep everywhere.
We will run the model under this new configuration (new vertical grid and modified bathymetry) and analyze how/if DSW formation and overflows changed. The issues involved in this test will be tagged as H2. For simplicity, the experiment that will derive from here can be named 01deg_jra55v13_ryf9091_**5m**"
