### ISSUE TITLE
[H1] Run ACCESS-OM2-01 with CM2 atmosphere

### ISSUE THREAD

**Issue by willaguiar** [willaguiar/DSW-collaborative-project#2]
Experiment: 01deg_jra55v13_ryf9091_CM2atm

edit April 28th: Simulation running its first year

[Read H1 for more information](https://github.com/willaguiar/DSW-collaborative-project#h1---wind-forcing)

**Comment by adele157** [comment]
You know, I think it could be interesting to try bias correcting the CM2 winds and forcing ACCESS-OM2-01 with those to start. i.e. Add a constant factor - or seasonally varying factor - so that the climatological CM2 winds roughly match those of JRA55. I'm wondering if even with good winds if we might not get DSW production, e.g. if the sea ice distribution (i.e. polynyas) is imprinted on other JRA55 fields apart from the winds and if those other fields might be important also. We know that with JRA55 forcing, our sea ice distribution matches obs really well, but I expect that won't be the case with CM2 winds, even with the bias correcting of the winds. Might be a good starting point at least to see for the case where the mean winds match those of JRA, how does the DSW compare with ACCESS-OM2-01.

**Comment by willaguiar** [comment]
ok, I was checking the delta(CM2atm-CTRL) $\tau_{x}$ and $\tau_{y}$ output fields and comparing with the delta $U_{10m}$ , $V_{10m}$ forcing fields. They are similar-ish (figs below,  [or check the end of  updated Wilma's code](https://github.com/willaguiar/DSW-collaborative-project/blob/39d4bcc1c7cf25a1aa224210d1488bc0d4c15dc7/JupyterCodes/CM2_bias_perturbation_setup.ipynb)). But there are some regions in the North Atlantic/North Pacific where changes in  $\tau_{x}$ and $\tau_{y}$ seem to be bigger than expected based on the change in winds.... Is that normal/expected?
@wghuneke @adele157 
<img width="1168" alt="Screen Shot 2023-05-12 at 4 17 42 PM" src="https://github.com/willaguiar/DSW-collaborative-project/assets/70033934/907d462e-eb7d-4f76-ae23-f1dd88e42d5c">
<img width="1173" alt="Screen Shot 2023-05-12 at 4 17 34 PM" src="https://github.com/willaguiar/DSW-collaborative-project/assets/70033934/e1500c59-5414-4f18-be2b-e27018d8f06f">

**Comment by adele157** [comment]
Maybe feedbacks from changes in sea ice moderating how much of the momentum input actually gets to the ocean?

**Comment by wghuneke** [comment]
I agree, especially the Labrador Sea is mostly ice-covered in CM2 while it's ice-free in obs/JRA. I guess this is the downside of applying the CM2 bias globally compared with only over the Southern Ocean.
